%YAML 1.2
---
split_kind : "instances" # instances,query,...;
random_split: "random" # random,custom
num_instances : 1
seed : 1
max_set_len : 5000
num_bins : 250

#gpu: 0
traindata_dir : "LatencyCollectorResults/new"
### different splits here
tags: "exp3_single,exp4_single_ergast,exp5_single_stats,exp6_single_joblight,exp8_single_stack,exp9_single_tpch,exp10_single_zdbs"
use_eval_tags : 1
eval_dirs : "LatencyCollectorResults/new"
eval_tags : "exp1_single,exp2_single"

dataset:
  input_train: ''
  input_test: ''
common:
  batch_size: 16
plan_net:
  arch: "gcn"
  hl: 512
  num_conv_layers: 4
  subplan_ests: 0
  dropout : 0.2
sys_net:
  # mlp / transformer
  #arch: "avg"
  #arch: "mlp"
  arch: "transformer"
  pretrained : 0
  use_pretrained_norms: 0
  save_weights: 0
  pretrained_fn: null

  hl: 512
  num_layers: 8
  num_heads: 16
  log_prev_secs: 600
  log_skip: 2

factorized_net:
  arch: "mlp" # dot product
  embedding_size: 128
  #arch: "dot"
  #embedding_size: 32
  pretrained: 0
  hl: 256
  num_layers: 2
...
