%YAML 1.2
---
#gpu: 0
traindata_dir : "LatencyCollectorResults"
tags : "CEB-t2medium-gp2"

use_eval_tags : 1
eval_dirs : "LatencyCollectorResults/multiple,LatencyCollectorResults"
eval_tags: "CEB-t2small-gp3,CEB-t2medium-gp3,JOB-t2medium-gp3"

dataset:
  input_train: ''
  input_test: ''
common:
  batch_size: 16
plan_net:
  arch: "gcn"
  hl: 512
  num_conv_layers: 4
  subplan_ests: 0
sys_net:
  # mlp / transformer
  arch: "transformer"
  hl: 256
  num_layers: 4
  num_heads: 16
  log_prev_secs: 200
  log_skip: 2

factorized_net:
  #arch: "mlp" # dot product
  arch: "dot"
  hl: 256
  num_layers: 2
  embedding_size: 16
...
