%YAML 1.2
---
split_kind : "query" # instances,query,...;
random_split: "random" # random,custom
num_instances : 1
seed : 1
ignore_node_feats: "Alias,Filter"

max_set_len : 50
num_bins : 25

#traindata_dir : "LatencyCollectorResults/new,LatencyCollectorResults/multiple,LatencyCollectorResults,LatencyCollectorResults/background"
traindata_dir : "LatencyCollectorResults/new,LatencyCollectorResults/multiple,LatencyCollectorResults,"

latent_variable: 1
latent_inference: 0
#num_latents: 128
num_latents: 8

## incl. background
#tags: "exp4_single_ergast,exp5_single_stats,exp8_single_stack,exp9_single_tpch,exp10_single_zdbs,exp11_single_zdbs,exp11_multi4_stack,exp12_multi4_tpch_stats_ergast,exp2_stack,exp3_stack_multi1,exp5_tpch_stats_ergast,exp9_stack1,exp9_stack2,"

#tags: "exp4_single_ergast,exp8_single_stack,exp9_single_tpch,exp10_single_zdbs"
tags: "exp4_single_ergast,exp8_single_stack,exp9_single_tpch"

use_eval_tags : 1
eval_dirs : "LatencyCollectorResults/new"
eval_tags : "exp1_single,exp2_single,exp3_single"

common:
  batch_size: 16
plan_net:
  arch: "gcn"
  hl: 512
  num_conv_layers: 8
  subplan_ests: 0
  dropout : 0.2
  pretrained: 0

hist_net:
  # mlp / transformer
  arch: "transformer"
  pretrained : 0
  save_weights: 1

  max_pool: 0
  hl: 32
  num_layers: 4
  num_heads: 16
  dropout: 0.2

sys_net:
  # mlp / transformer
  arch: "transformer"
  pretrained : 0
  save_weights: 1
  #pretrained_fn: "models2/noimdb_128_filters_actual.wt"
  #pretrained_fn: "models3/noimdb_128_actual_ae.wt"
  #pretrained_fn: "models3/noimdb_128_actual_ae_fact2.wt"

  #pretrained_fn: "models3/noimdb_128_ae.wt"

  #pretrained_fn: "models3/noimdb_128_ae_actual_incl_bg.wt"
  #pretrained_fn: "models3/noimdb_128_ae_actual.wt"

  #pretrained_fn: "models3/noimdb_128_ae_include-exp1.wt"

  #pretrained_fn: "models3/hist_heuristic_latent_noimdb.wt"

  #pretrained_fn: "models3/hist_heuristic_latent_noimdb_ystd.wt"

  #pretrained_fn: "models3/hist_heuristic_latent_noimdb_ystd_small.wt"
  pretrained_fn: "models3/hist_heuristic_latent_noimdb_ystd_small2.wt"

  max_pool: 1
  hl: 512
  num_layers: 4
  num_heads: 16
  log_prev_secs: 600
  log_skip: 2
  dropout: 0.2

factorized_net:
  arch: "mlp" # dot product
  embedding_size: 4
  hl: 16

  pretrained: 0
  num_layers: 4
  dropout: 0.2
  heuristic_feats: 1
...
