%YAML 1.2
---
split_kind : "query" # instances,query,...;
random_split: "random" # random,custom
num_instances : -1
seed : 1
ignore_node_feats: "Alias,"

max_set_len : 50000
num_bins : 5000
#num_bins : 1000

#gpu: 0
traindata_dir : "LatencyCollectorResults/background,LatencyCollectorResults/new,LatencyCollectorResults/multiple,LatencyCollectorResults"
#traindata_dir : "LatencyCollectorResults/background,LatencyCollectorResults/new"

#tags: "exp1_single,exp2_single,exp3_single,exp1,exp2_stack,exp3_stack_multi1,exp4_ceb2,exp4_single_ergast,exp5_single_stats,exp6_single_joblight,exp7_single_ceb2,exp8_single_stack,exp9_single_tpch,exp10_single_zdbs,exp11_single_zdbs,t7xlarge-gp3-c,t7xlarge-gp3-d,t7xlarge-gp3-e-stressng,t7xlarge-gp3-f-stressng"
#tags: "exp1"

#tags: "exp2_stack,exp4_ceb2,exp5_tpch_stats_ergast,exp3_stack_multi1"
#tags: "exp2_stack,exp4_ceb2,exp5_tpch_stats_ergast,exp3_stack_multi1,exp6_multi4b,exp7_multi4,exp9_stack1,exp9_stack2,exp10_multi4_1p"

#tags: "exp6_multi4b,exp7_multi4,exp9_stack1,exp9_stack2,exp10_multi4_1p"
#tags: "exp9_stack1,exp9_stack2,exp10_multi4_1p_imdb,exp11_multi4_stack"

## p2 bg load
tags: "exp7_multi4"

## simple bg load, no time limit etc., chess-training-data
#tags: "exp6_multi4,exp6_multi4b"

## all-imdb 1p loads
#tags: "exp6_multi4,exp6_multi4b,exp10_multi4_1p_imdb"

## all-stack 1p loads
#tags: "exp9_stack1,exp9_stack2,exp11_multi4_stack"

use_eval_tags : 0
eval_dirs : "LatencyCollectorResults/new"
eval_tags : "exp2_single"

dataset:
  input_train: ''
  input_test: ''
common:
  batch_size: 16
plan_net:
  arch: "gcn"
  hl: 512
  num_conv_layers: 4
  subplan_ests: 0
  dropout : 0
sys_net:
  # mlp / transformer
  arch: "transformer"
  pretrained : 0
  save_weights: 1
  #pretrained_fn: "models2/bg_imdball_attention.wt"
  #pretrained_fn: "models2/bg_imdball_mlp.wt"
  #pretrained_fn: "models2/single_noimdbwk_bg_stack_attention.wt"
  #pretrained_fn: "models2/bg_exp2_exp5.wt"
  #pretrained_fn: "models2/bg_debug2.wt"
  #pretrained_fn: "models2/allbg_debug.wt"
  #pretrained_fn: "models2/bg_stack_attention_fact4.wt"
  #pretrained_fn: "models2/bg_stack_attention_small.wt"
  #pretrained_fn: "models2/bg_stack_attention_larger.wt"
  #pretrained_fn: "models2/bg_stack_ceb2_attention.wt"
  #pretrained_fn: "models2/all_noimdbwk_attention.wt"
  #pretrained_fn: "models2/all_attention.wt"
  #pretrained_fn: "models2/all_attention_100bins.wt"

  #pretrained_fn: "models2/bg_multi4.wt"
  #pretrained_fn: "models2/bg_multi4_stack1p.wt"
  pretrained_fn: "models2/bg_multi4_imdb2p.wt"

  hl: 512
  ## normal
  num_layers: 8
  num_heads: 16

  #small
  #num_layers: 4
  #num_heads: 4

  ## larger
  #num_layers: 16
  #num_heads: 16

  log_prev_secs: 600
  log_skip: 2

factorized_net:
  #arch: "mlp" # dot product
  arch: "attention"
  embedding_size: 128
  pretrained: 1
  hl: 256
  num_layers: 2
  #num_layers: 1 # 4
...
