%YAML 1.2
---
split_kind : "instances" # instances,query,...;
random_split: "random" # random,custom
num_instances : 1
seed : 1

max_set_len : 1000
num_bins : 100

#gpu: 0
traindata_dir : "LatencyCollectorResults/new,LatencyCollectorResults/background"
###tags: "exp4_single_ergast,exp5_single_stats,exp6_single_joblight,exp7_single_ceb2,exp8_single_stack,exp9_single_tpch,exp10_single_zdbs,exp11_single_zdbs"

### different splits here
#tags: "exp1_single,exp2_single,exp3_single"
#tags: "exp2_stack"
#tags: "exp10_single_zdbs"
#tags: "exp1"
#tags: "exp1"
tags: "exp8_single_stack"
#tags: "exp2_stack"

use_eval_tags : 0
eval_dirs : "LatencyCollectorResults/new"
#eval_tags : "exp1_single"
eval_tags : "exp1_single,exp2_single"

dataset:
  input_train: ''
  input_test: ''
common:
  batch_size: 16
plan_net:
  arch: "gcn"
  hl: 512
  num_conv_layers: 8
  subplan_ests: 0
  dropout : 0.2
sys_net:
  # avg/ mlp / transformer
  arch: "transformer"
  pretrained : 0
  max_pool : 0
  use_pretrained_norms: 0
  save_weights: 0
  pretrained_fn: null

  hl: 512
  num_layers: 2
  num_heads: 32
  log_prev_secs: 600
  log_skip: 2

factorized_net:
  #arch: "mlp" # dot product
  arch: "dot" # dot product
  embedding_size: 128
  #arch: "dot"
  #embedding_size: 32
  pretrained: 0
  hl: 256
  num_layers: 2
...
