%YAML 1.2
---
#split_kind : "query" # instances,query,...;
split_kind : "instances" # instances,query,...;
random_split: "random" # random,custom
num_instances : 1
seed : 1
#max_set_len : 5000
#num_bins : 250

max_set_len : 1000
num_bins : 100

latent_variable: 1
latent_inference: 1
num_latents: 128

#gpu: 0
traindata_dir : "LatencyCollectorResults/background"
tags: "exp2_stack,exp3_stack_multi1"

#tags: "exp3_stack_multi1"
use_eval_tags : 0
eval_dirs : "LatencyCollectorResults/new"
eval_tags : "exp1_single,exp2_single"

dataset:
  input_train: ''
  input_test: ''
common:
  batch_size: 16
plan_net:
  arch: "gcn"
  hl: 512
  num_conv_layers: 8
  subplan_ests: 0
  dropout : 0.2
  pretrained: 0

sys_net:
  arch: "transformer"
  pretrained : 1
  use_pretrained_norms: 1
  save_weights: 0
  max_pool: 1
  dropout: 0.2

  #pretrained_fn: "models2/noimdb_128_filters_actual_fixed.wt"
  #pretrained_fn: "models2/noimdb2_attention.wt"
  #pretrained_fn: "models2/bg_imdball_attention.wt"

  #pretrained_fn: "models2/all_attention.wt"
  #pretrained_fn: "models2/all_attention_bins50.wt"

  #pretrained_fn: "models2/bg_stack_attention.wt"
  #pretrained_fn: "models2/bg_imdball_mlp.wt"

  ## includes imdb (ceb-2 and joblight)
  #pretrained_fn: "models/all_noimdb_128_col1_fixed.wt"

  ## other background processes
  #models2/bg_multi4.wt

  hl: 512
  num_layers: 8
  num_heads: 16
  log_prev_secs: 600
  log_skip: 2

  ### latent models
  pretrained_fn: "models3/latent_nostack_ae2.wt"

factorized_net:
  #arch: "attention" # dot product
  arch: "mlp"
  embedding_size: 128
  num_layers: 2
  pretrained: 1
  hl: 256
  dropout: 0.2
...
