%YAML 1.2
---
split_kind : "lt_type" # instances,query,...;
random_split: "random" # random,custom
num_instances : 1
seed : 1
ignore_node_feats: "Alias,Filter,MergeCond,SortKey,GroupKey,HashCond,SubplanName"
#ignore_node_feats: ""

max_set_len : 100
num_bins : 25

latent_variable: 0
num_latents: 128
latent_inference: 0

traindata_dir : "LatencyCollectorResults/new,LatencyCollectorResults/multiple,LatencyCollectorResults"

#tags: "exp4_single_ergast,exp8_single_stack,exp9_single_tpch,exp7_single_ceb2"
tags : "exp1_single,exp2_single,exp3_single"

use_eval_tags : 0
eval_dirs : "LatencyCollectorResults/new"
eval_tags : "exp1_single,exp2_single,exp3_single"
#eval_tags : "exp1_single,exp3_single"

common:
  batch_size: 16
plan_net:
  arch: "gcn"
  hl: 512
  num_conv_layers: 8
  subplan_ests: 0
  dropout : 0.2
  pretrained: 1

hist_net:
  # mlp / transformer
  arch: "transformer"
  pretrained : 1
  save_weights: 0

  max_pool: 0
  hl: 32
  num_layers: 4
  num_heads: 32
  dropout: 0.2

sys_net:
  # mlp / transformer
  arch: "transformer"
  pretrained : 1
  save_weights: 0
  use_pretrained_norms: 1

  pretrained_fn: "models3/pretrain_all-no_imdb.wt"

  max_pool: 0
  hl: 512
  num_layers: 4
  num_heads: 16
  log_prev_secs: 600
  log_skip: 2
  dropout: 0.2

factorized_net:
  arch: "mlp" # dot product
  embedding_size: 128
  pretrained: 0
  hl: 256
  num_layers: 4
  dropout: 0.2
  heuristic_feats: 1
...
