%YAML 1.2
---
#split_kind : "query" # instances,query,...;
split_kind : "instances" # instances,query,...;
random_split: "random" # random,custom
num_instances : 1
seed : 1
#max_set_len : 5000
#num_bins : 250

max_set_len : 1000
num_bins : 100

#gpu: 0
traindata_dir : "LatencyCollectorResults/background"
tags: "exp2_stack"
#tags: "exp3_stack_multi1"
use_eval_tags : 0
eval_dirs : "LatencyCollectorResults/new"
eval_tags : "exp1_single,exp2_single"

dataset:
  input_train: ''
  input_test: ''
common:
  batch_size: 16
plan_net:
  arch: "gcn"
  hl: 512
  num_conv_layers: 4
  subplan_ests: 0
  dropout : 0.2
sys_net:
  arch: "transformer"
  pretrained : 1
  use_pretrained_norms: 1
  save_weights: 0

  pretrained_fn: "models2/all_attention.wt"

  hl: 512
  num_layers: 8
  num_heads: 16
  log_prev_secs: 600
  log_skip: 2

factorized_net:
  arch: "attention" # dot product
  embedding_size: 128
  #arch: "dot"
  #embedding_size: 32

  num_layers: 2
  pretrained: 1
  hl: 256

  #arch: "mlp" # dot product
  #num_layers: 2
...
