%YAML 1.2
---
#split_kind : "query" # instances,query,...;
split_kind : "instances" # instances,query,...;
random_split: "random" # random,custom
num_instances : 1
seed : 1
#max_set_len : 5000
#num_bins : 250
latent_variable: 1
num_latents: 128
latent_inference: 0


max_set_len : 1000
num_bins : 100

#gpu: 0
traindata_dir : "LatencyCollectorResults/new"
#tags: "exp2_single,exp3_single,"
tags: "exp1_single,exp2_single,exp3_single"
use_eval_tags : 0
eval_dirs : "LatencyCollectorResults/new"
eval_tags : "exp1_single,exp2_single"
#eval_tags : "exp1_single"

dataset:
  input_train: ''
  input_test: ''
common:
  batch_size: 16
plan_net:
  arch: "gcn"
  hl: 512
  num_conv_layers: 4
  subplan_ests: 0
  dropout : 0.0
  pretrained: 0
hist_net:
  # mlp / transformer
  arch: "transformer"
  pretrained : 1
  save_weights: 1

  max_pool: 0
  hl: 32
  num_layers: 2
  num_heads: 16
  dropout: 0.2

sys_net:
  # mlp / transformer
  #arch: "avg"
  #arch: "mlp"
  arch: "transformer"
  pretrained : 1
  use_pretrained_norms: 1
  save_weights: 0
  pretrained_fn: "models3/hist_heuristic_latent_stack-ergast-tpch.wt"

  hl: 512
  num_layers: 2
  num_heads: 16
  log_prev_secs: 600
  log_skip: 2
  dropout: 0.0

factorized_net:
  arch: "mlp" # dot product
  #arch: "attention"
  embedding_size: 128
  #arch: "dot"
  #embedding_size: 32
  pretrained: 1
  hl: 256
  num_layers: 2
  dropout: 0.2
  heuristic_feats: 1
...
