%YAML 1.2
---
#split_kind : "query" # instances,query,...;
split_kind : "instances" # instances,query,...;
random_split: "random" # random,custom
num_instances : 1
seed : 1

max_set_len : 1000
num_bins : 100

latent_variable: 1
latent_inference: 0
num_latents: 128

#gpu: 0
traindata_dir : "LatencyCollectorResults/new,LatencyCollectorResults/background"

#tags: "exp2_stack,exp3_stack_multi1"
#tags: "exp9_stack1,exp9_stack2,exp11_multi4_stack"

tags: "exp8_single_stack,exp2_stack,exp3_stack_multi1,exp9_stack1,exp9_stack2,exp11_multi4_stack"

#tags: "exp3_stack_multi1"
use_eval_tags : 0
eval_dirs : "LatencyCollectorResults/new"
eval_tags : "exp1_single,exp2_single"

dataset:
  input_train: ''
  input_test: ''
common:
  batch_size: 16
plan_net:
  arch: "gcn"
  hl: 512
  num_conv_layers: 8
  subplan_ests: 0
  dropout : 0.2
  pretrained: 0

#hist_net:
  ## mlp / transformer
  #arch: "transformer"
  #pretrained : 1
  #save_weights: 1

  #max_pool: 1
  #hl: 512
  #num_layers: 4
  #num_heads: 16
  #dropout: 0.2

sys_net:
  arch: "transformer"
  pretrained : 1
  use_pretrained_norms: 1
  save_weights: 0
  max_pool: 1
  dropout: 0.2

  hl: 512
  num_layers: 2
  num_heads: 16
  log_prev_secs: 600
  log_skip: 2

  ### latent models
  #pretrained_fn: "models3/latent_nostack_ae2.wt"

  #pretrained_fn: "models3/bg_noimdb.wt"
  pretrained_fn: "models3/noimdb_all2.wt"

factorized_net:
  #arch: "attention" # dot product
  arch: "mlp"
  embedding_size: 128
  num_layers: 2
  pretrained: 1
  hl: 256
  dropout: 0.2
  heuristic_feats: 1
...
