%YAML 1.2
---
split_kind : "query" # instances,query,...;
random_split: "random" # random,custom
num_instances : 1
seed : 1

max_set_len : 100
num_bins : 25

#gpu: 0
traindata_dir : "LatencyCollectorResults/new,LatencyCollectorResults/background,LatencyCollectorResults/multiple"

# multiple
#tags: "t7xlarge-gp3-c,t7xlarge-gp3-d,t7xlarge-gp3-e-stressng,t7xlarge-gp3-f-stressng"

## imdb splits
tags: "exp1_single,exp2_single,exp3_single,exp1,exp4_ceb2,exp7_multi4,exp10_multi4_1p_imdb,exp6_multi4,exp6_multi4b,exp10_multi4_1p_imdb2,exp7_single_ceb2"


use_eval_tags : 0
eval_dirs : "LatencyCollectorResults/new"
#eval_tags : "exp1_single"
eval_tags : "exp1_single,exp2_single"

dataset:
  input_train: ''
  input_test: ''
common:
  batch_size: 16
plan_net:
  arch: "gcn"
  hl: 512
  num_conv_layers: 4
  subplan_ests: 0
  dropout : 0.2
sys_net:
  # avg/ mlp / transformer
  arch: "transformer"
  pretrained : 0
  use_pretrained_norms: 0
  save_weights: 0
  pretrained_fn: null
  max_pool: 0

  hl: 512
  num_layers: 2
  num_heads: 32
  log_prev_secs: 600
  log_skip: 2

factorized_net:
  arch: "mlp" # dot product
  #arch: "dot" # dot product
  embedding_size: 128
  #arch: "dot"
  #embedding_size: 32
  pretrained: 0
  hl: 256
  num_layers: 2
...
